
from params import *
import math
from scipy.integrate import solve_ivp
import numpy as np

# =========================================================================
# Biological / MPC equations
# =========================================================================

# =========================== Growth Equation Taken from the paper =================================

def tao(t: float) -> float:
    """Temperature effect τ(T). 
    From paper"""
    if t > T_opt:
        return math.exp(-k * ((t - T_opt) / (T_max - T_opt))**4)
    if t < T_opt:
        return math.exp(-k * ((T_opt - t) / (T_opt - T_min))**4)
    return 1.0


def segma(x: float) -> float:
    """Dissolved oxygen limitation function σ(DO).
    paper"""
    if x >= DO_crt:
        return 1.0
    if DO_min < x < DO_crt:
        return (x - DO_min) / (DO_crt - DO_min)
    return 0.0


def v(x: float) -> float:
    """Unionized ammonia effect v(UIA).
    paper"""
    if x < UIA_crit:
        return 1.0
    if UIA_crit < x < UIA_max:
        return (UIA_max - x) / (UIA_max - UIA_crit)
    return 0.0


def dwdt(t: float, w: float, UIA: float, f: float, T: float, DO: float) -> float:
    """
    Main growth ODE: dw/dt as a function of weight, UIA and feed ratio.
    f is feeding ratio (fraction of body weight per day).
    Equation taken from "MPC paradigms for fish growth reference tracking in precision 
    aquaculture" research paper, we are treating p as a constant (0<p<2).
    """
    w = max(w, 0.0000001)
    growth = h * p * f * b * (1 - a) * tao(T) * 1 * 1 * w**m   #segma(DO) = 1, v(UIA) = 1 for calibration
    loss   = k_min * math.exp(j * (T - T_min)) * w**n
    return growth - loss

# =======================================================================================
#                     Water Quality Equations - Yellow Book
# =======================================================================================

def ammonia(TAN: float) -> float:
    """
    Ammonia caclulation from page 42
    """
    pKa = PK_a # for now its a const
    pH = PH_cons # for now
    NH3_N = TAN / (1 + 10 ** (pKa - pH))
    
    return NH3_N


def phi(co2: float) -> float:
    """CO2 limit function
    UNUSED!!!! + I dont know where its from"""
    if co2 < CO2_crit:
        return 1.0
    if CO2_crit <= co2 < CO2_max:
        return 1.0 - (co2 - CO2_crit) / (CO2_max - CO2_crit)
    return 0.0


def CO2(ALK: float, pH: float) -> float:
    """
    CO2 consentration (mg/L) approximation (5-10%), page 51
    Unused
    """
    ALK = Alk # const for now
    C_CO2 = ALK * 10**(6.3 - pH)
    
    return C_CO2


def update_water_quality(TAN_prev: float, NO3_prev: float, CO2_prev, feed_kg: float, Q_water: float) -> tuple:
    """
    
    """
    total_feed = feed_kg * N_fish   #scaling up for the whole tank (?)
   
    TAN_pool = ((total_feed * PC * 0.094) * 1000 ) / V_water + max(0.0, TAN_prev) 
    
    # Removal Capacity
    # Added max(0.0, TAN_pool) to prevent negative float errors in scalar power
    r_N_capacity = ((n_BF * (max(0.0, TAN_pool) ** k_BF)) * V_BF) / V_water
    r_N_actual = min(r_N_capacity, TAN_pool)
    
    TAN_bio = max(TAN_pool - r_N_actual, 0.0)
    
    # Update Nitrate
    NO3_bio = max(0.0, NO3_prev) + r_N_actual
    
    # Now wwe add CO2 production
    # fish produce approx 400g co2 per kg of feed
    CO2_prod = (total_feed * 400) / V_water 

    #CO2_bio  = CO2_prev + CO2_prod - (k_strip * (CO2_prev - 0.5))
    #CO2_bio  = max(CO2_bio, 0.5)
    C_eq = 0.5 # Equilibrium CO2
    dt = 1.0   # 1 day
    
    C_inf = C_eq + (CO2_prod / k_strip)
    CO2_bio = C_inf + (CO2_prev - C_inf) * math.exp(-k_strip * dt)

    # Dilution
    dilution_factor = min(Q_water/V_water, 1.0)

    TAN_next = TAN_bio * (1 - dilution_factor) + TAN_fresh * dilution_factor

    NO3_next = NO3_bio * (1 - dilution_factor) + NO3_fresh * dilution_factor
    CO2_next = CO2_bio * (1 - dilution_factor) + CO2_fresh * dilution_factor

    return TAN_next, NO3_next, CO2_next
   

# =======================================================================================
#                           Simulation function
# =======================================================================================

def run_sim(ind, initial_weight, initial_Tan, initial_Nitrate=0.0, initial_CO2 = 0.5):
    
    feeds      = [float(t[0]) for t in ind]    # from the individual generated by the GA, the first is the feed
    temps      = [float(t[1]) for t in ind]
    DOs        = [float(t[2]) for t in ind]
    Q_waters   = [float(t[3]) for t in ind]

    t_span = (0.0, 1.0)  # integrate over 1 day

    weights  = [initial_weight]
    tan_lst  = [initial_Tan]
    no3_lst  = [initial_Nitrate]
    co2_lst  = [initial_CO2]
    feeds_kg = []
    
    for day in range(len(ind)):

        w_current      = weights[-1]
        tan_tmp        = tan_lst[-1]
        no3_tmp        = no3_lst[-1]
        co2_tmp        = co2_lst[-1]

        UIA_current = ammonia(tan_tmp)

        current_feed = feeds[day]
        current_temp = temps[day]
        current_DO   = DOs[day]
        current_Q    = Q_waters[day]

        sol = solve_ivp(
            lambda t, w: dwdt(t, w, UIA_current, current_feed, current_temp, current_DO),
            t_span,
            [w_current],
            t_eval=[t_span[1]]
        )

        if not sol.success:
            raise RuntimeError(f"ODE failed on day {day}: {sol.message}")

        w_tmp = sol.y[0, -1]
        weights.append(w_tmp)

        # Update TAN, feed and nitrate
        feed_kg = current_feed * w_current
        tan_tmp, no3_tmp, co2_tmp= update_water_quality(tan_tmp, no3_tmp,
                                                         co2_tmp, feed_kg, 
                                                         current_Q)
        
        tan_lst.append(tan_tmp)
        no3_lst.append(no3_tmp)
        co2_lst.append(co2_tmp)
        feeds_kg.append(feed_kg)

    return weights, feeds_kg, tan_lst, no3_lst, co2_lst, temps, DOs, Q_waters


def profit(w_final: float,
           w_initial: float,
           f_list,
           T_list,
           DO_list,
           Q_list,
           days) -> float:
    """
    Bio-economic profit for a given period.

    :param w_final:  final fish weight (kg)
    :param w_initial: initial fish weight (kg)
    :param f_list:   list of feed amounts in kg over the period
    :param T:        water temperature (°C)
    :param DO:       dissolved oxygen (mg/L)
    :param days:     number of days in this profit period
    """

    assert len(f_list) == len(T_list) == len(DO_list) == days

    # ================= Revenue =================
    revenue = (w_final - w_initial) * p_fish * N_fish

    # ================= Feed cost =================
    total_feed = 0
    
    for f in f_list:
        total_feed += f

    feed_cost = total_feed * p_feed * N_fish

   # ================= Electricity costs =================

    heat_cost = 0.0
    DO_cost   = 0.0
    water_cost= 0.0

    for T, DO, Q in zip(T_list, DO_list, Q_list):
        T  = float(np.asarray(T).squeeze())
        DO = float(np.asarray(DO).squeeze())
        Q  = float(np.asarray(Q).squeeze())

        heat_flux_surf = area * 12.12 * max(0.0, T - T_env) #/ N_fish

        heat_flux_ex   = (Q * 1000.0 * Cp_water * (T - T_fresh))/ (24 * 3600)

        total_heat = heat_flux_surf + (heat_flux_ex) #/ N_fish)
        heat_cost += (total_heat / 1000.0) * electricity_price * 24.0

        water_cost += (Q * p_water) #/ N_fish

        DO_extra = max(0.0, DO - DO_base)
        DO_cost_per_m3 = ((DO_extra / 1000.0) / 0.46) * electricity_price
        DO_cost += DO_cost_per_m3 * (V_water) #/ N_fish)

    # ================= Total cost =================

    total_cost = feed_cost + heat_cost + DO_cost + water_cost
    
    return revenue - total_cost

#========================================================================================